models/Program.php
<?php
/**
 * Created by PhpStorm.
 * User: mx
 * Date: 18.07.15
 * Time: 10:13
 */
namespace app\models;

use yii\db\ActiveRecord;

class Program extends ActiveRecord
{

    /**
     * user id attribut wich can be transmitted from post data
     */
    const USER_ID_ATTR_NAME = 'user_id';

    public function rules()
    {
        return [
            [['title'], 'required'],
//            [['title', 'text', 'parent_id'], 'required'],
//            ['parent_id', 'integer'],
        ];
    }


    public function getExercises() {
        return $this->hasMany(Exercise::className(), ['id' => 'exercise_id'])
          ->viaTable('program_exercise', ['program_id' => 'id']);
    }


    public function create()
    {
        $user = \Yii::$app->user->identity;
        $userId = $user ? $user->id : 0;

        if ($this->hasAttribute(self::USER_ID_ATTR_NAME)) {
            $this->setAttribute(self::USER_ID_ATTR_NAME, $userId);
        }

        if ($this->validate() && $this->save(true)) {
            return true;
        } else {
            die('No record was created');
        }
    }

    public function getProgramById($id)
    {
        $program = $this::find()
            ->where(['program_id' => $id])
            ->one();

        var_dump($id);
        return $program;
    }


    public function deleteById($program_id)
    {
        $this::deleteAll('program_id = :id', [':id' => $program_id]);
    }

    private function getChildNodes()
    {

    }
}

controllers/ProgramController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\Program;
use app\models\Exercise;
use yii\helpers\Url;

class ProgramController extends Controller
{

    public function actionIndex()
    {
        $query = Program::find();

        $pagination = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $programs = $query->orderBy(['created_at' => SORT_DESC])
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();


        $this->layout = '/clean';
        return $this->render('index', [
            'programs' => $programs,
            'pagination' => $pagination,
        ]);
    }

    public function actionCreate()
    {

        $model = new Program();
        $request = Yii::$app->request;

        if($request->getIsPost()) {
            $model->load($request->post());
            if ($model->create()) {
                return $this->redirect(Url::toRoute(['program/details', 'program_id' => $model->program_id]));
            };
        }
        $this->layout = '/clean';
        return $this->render('create', [
            'model' => $model
        ]);
    }

    public  function actionDelete()
    {
        $request = Yii::$app->request;
        if ($request->getIsGet()) {
            if ($postId = $request->get('post_id')) {
                $model = new Post();
                $model->deleteById($postId);
            }
        }
        return $this->goBack();
    }

    public  function actionEdit()
    {
        $model = new Post();
        $request = Yii::$app->request;
        if ($request->getIsPost()) {
            $model->load($request->post());
            if ($model->create()) {
                return $this->redirect(Url::toRoute('post/index'));
            };
        }
        $postId = $request->get('post_id');
        $postData = $model->getPostDataById($postId);
        if($request->getIsGet() && $request->get('post_id')) {
            $model->setAttributes($postData->getAttributes());
        }
        $this->layout = '/clean';
        return $this->render('edit', [
            'model' => $model,
        ]);
    }

    public function actionDetails()
    {
        $query = Exercise::find();
        $request = Yii::$app->request;
        $programId = $request->get('program_id');

        // $exercises = $query->where('program_id = :id ', ['id'=>$programId])->all();
        $exercises = $query->all();


        $this->layout = '/clean';
        return $this->render('details', [
            'exercises' => $exercises,
            'programId' => $programId,
        ]);
    }


    public function actionCreateExercise()
    {
        $exercise = new Exercise();
        $request = Yii::$app->request;
        $programId = $request->get('program_id');

        if($request->getIsPost()) {
            $programId = $request->post('program_id');
            $programModel = new Program();
            $program = $programModel->getProgramById($programId);
            $exercise->load($request->post());

            if ($exercise->create()) {
                $exercise->link('programs', $program);
                return $this->redirect(Url::toRoute('program/details'));
            };
        }

        $this->layout = '/clean';

        return $this->render('exercise/create', [
            'exercise' => $exercise,
            'programId' => $programId,
        ]);
    }

}

views/program/create.php
<?php
use yii\helpers\Url;
use app\models\User;
use yii\widgets\LinkPager;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Новая программа';
?>

<h1><?= Html::encode($this->title) ?></h1>

<?php
    $form = ActiveForm::begin([
        'id' => 'new-programm-form',
        'options' => ['class' => 'custom-form hidden'],
        'fieldConfig' => [
            'template' => "{label}{input}{error}",
            'labelOptions' => [
                // 'class' =>   'col-lg-1 control-label'
            ],
        ],
    ]);
?>

<?= $form->field($model, 'title') ?>

<div class="form-group">
    <?= Html::submitButton('Save', ['class' => 'btn btn-info', 'name' => 'new-programm-button']) ?>
</div>

<?php ActiveForm::end(); ?>

    <div class="row">
        <div class="col-lg-8">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="col-lg-1">#</th>
                    <th class="col-lg-6">Упражнение</th>
                    <th class="col-lg-1">Отягощение</th>
                    <th class="col-lg-1">Подходы</th>
                    <th class="col-lg-1">Повторения</th>
                    <th class="col-lg-2">Отдых между подходами</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>Жим лежа</td>
                        <td>75</td>
                        <td>3</td>
                        <td>8</td>
                        <td>40 сек</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Швунг</td>
                        <td>45</td>
                        <td>3</td>
                        <td>12</td>
                        <td>20 сек</td>
                    </tr>
                    <tr>
                        <td colspan="6" align="center">
                            <div class="custom-table-button">
                                Добавить упражение
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

views/program/details.php
<?php
use yii\helpers\Url;
use app\models\User;
// use yii\widgets\LinkPager;

$currentUser = \Yii::$app->user->getIdentity();
?>

<div class="btn-container">

    <h1><?php echo $programId ?></h1>

    <a class="button btn-info btn" href="<?= Url::toRoute(['program/create-exercise', 'program_id' => $programId])?>">Add New Exercise</a>
</div>

<div class="post-list-wrp">
    <?php if (count($exercises) > 0 ): ?>
        <table class="exercises-table table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Approach Count</th>
                    <th>Repeats</th>
                    <th>Additional Weight</th>
                    <th>Time</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($exercises as $_exercise): ?>
                    <tr>
                        <td><?= $_exercise->name ?></td>
                        <td><?= $_exercise->approach_count ?></td>
                        <td><?= $_exercise->repeats ?></td>
                        <td><?= $_exercise->burdening ?></td>
                        <td><?= $_exercise->timing ?></td>
                        <td><?= $_exercise->description ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

    <?php else: ?>
        <span class="no-programs">There is no available exercises.</span>
    <?php endif;?>
</div>

views/program/index.php
<?php
use yii\helpers\Url;
use app\models\User;
use yii\widgets\LinkPager;
$currentUser = \Yii::$app->user->getIdentity();
?>


<h1>Мои программы</h1>

<?php if(!Yii::$app->user->isGuest): ?>
    <?php if (count($programs) > 0 ): ?>
        <ul class="post-list">
            <?php foreach ($programs as $_program): ?>
                <?php $url = Url::toRoute(['program/details', 'program_id' => $programId]); ?>
                <li><a href="<?= $url ?>"><?= $_program->title ?></a></li>
            <?php endforeach; ?>
        </ul>
        <?= LinkPager::widget(['pagination' => $pagination]) ?>
    <?php else: ?>
        <p class="no-programs">Программы не созданы</p>
    <?php endif;?>

    <div class="buttons-wrapper">
        <a class="btn btn-info" href="<?= Url::toRoute('program/create') ?>">Create New Program</a>
    </div>
<?php endif;?>